# Generated by Django 4.2.1 on 2023-08-24 20:19

from django.db import migrations, models

import core.models
import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    core.models.UniqIDField(
                        default=core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="Post ID")),
                ("message", models.TextField(blank=True, null=True, verbose_name="Message")),
                ("reply", models.TextField(blank=True, null=True, verbose_name="Reply Content")),
                (
                    "openai_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name="OpenAI ID"),
                ),
                ("model", models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name="Model")),
                ("duration", models.IntegerField(blank=True, null=True, verbose_name="Duration(ms)")),
                ("prompt_tokens", models.IntegerField(blank=True, null=True, verbose_name="Prompt Tokens Count")),
                (
                    "completion_tokens",
                    models.IntegerField(blank=True, null=True, verbose_name="Completion Tokens Count"),
                ),
                ("total_tokens", models.IntegerField(blank=True, null=True, verbose_name="Total Tokens Count")),
                ("is_success", models.BooleanField(db_index=True, verbose_name="Is Success")),
                ("created_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Create Time")),
            ],
            options={
                "verbose_name": "Chat Log",
                "verbose_name_plural": "Chat Log",
                "ordering": ["-created_at"],
            },
        ),
    ]
